#!/usr/bin/env bash

BREW_BIN="$(brew --prefix)/bin"
ANACONDA_DIR="$HOME/anaconda"
ANACONDA_BIN="$ANACONDA_DIR/bin"
ANACONDA_ENVS="$ANACONDA_DIR/envs"
BREW_ENV_DIR="$ANACONDA_ENVS/brew"
BREW_ENV_BIN="$BREW_ENV_DIR/bin"
SYSTEM_ENV_DIR="$ANACONDA_ENVS/system"
SYSTEM_ENV_BIN="$SYSTEM_ENV_DIR/bin"
CONDA_CONFIG_DIR="$HOME/.conda"
CONDA_CONFIG_ENVS="$CONDA_CONFIG_DIR/environments.txt"

mkdir -p "$CONDA_CONFIG_DIR" && touch "$CONDA_CONFIG_ENVS"
echo "$BREW_ENV_DIR" >> "$CONDA_CONFIG_ENVS"
echo "$SYSTEM_ENV_DIR" >> "$CONDA_CONFIG_ENVS"

mkdir -p "$BREW_ENV_BIN"
pushd "$BREW_ENV_BIN" > /dev/null
ln -fs "$ANACONDA_BIN/conda"
ln -fs "$ANACONDA_BIN/activate"
ln -fs "$ANACONDA_BIN/deactivate"
ln -fs "$BREW_BIN/2to3"
ln -fs "$BREW_BIN/easy_install"
ln -fs "$BREW_BIN/idle"
ln -fs "$BREW_BIN/pip"
ln -fs "$BREW_BIN/pydoc"
ln -fs "$BREW_BIN/python"
ln -fs "$BREW_BIN/python-config"
ln -fs "$BREW_BIN/pythonw"
ln -fs "$BREW_BIN/smtpd.py"
ln -fs "$BREW_BIN/wheel"
popd > /dev/null

mkdir -p "$SYSTEM_ENV_BIN"
pushd "$SYSTEM_ENV_BIN" > /dev/null
ln -fs "$ANACONDA_BIN/conda"
ln -fs "$ANACONDA_BIN/activate"
ln -fs "$ANACONDA_BIN/deactivate"
ln -fs "/usr/bin/2to3"
ln -fs "/usr/bin/easy_install"
ln -fs "/usr/bin/idle"
ln -fs "/usr/bin/pip"
ln -fs "/usr/bin/pydoc"
ln -fs "/usr/bin/python"
ln -fs "/usr/bin/python-config"
ln -fs "/usr/bin/pythonw"
ln -fs "/usr/bin/smtpd.py"
ln -fs "/usr/bin/wheel"
popd > /dev/null
